apiVersion: v1
kind: Service
metadata:
  annotations:
    service.antrea.io/external-ip-pool: "service-external-ip-pool"
  labels:
    app: longhorn-ui
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.8.1
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: longhorn-ui
  loadBalancerIP: "192.168.1.221"
  type: LoadBalancer
