apiVersion: v1
kind: PersistentVolume
metadata:
   name: nfs-pvol-siem
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/shared
    server: k8s-master-01 # Usar nombre en /etc/hosts del master
    readOnly: false
  storageClassName: nfs-sc-siem