{
 "title": "IDS Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Suricata Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs Suricata",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"suricata\"} \n|  json \n|  line_format \"{{.flow_start}} 🛡️ Intento de ataque tipo: {{.signature_text}} con firma {{.signature_id}} desde el origen {{.src_ip}}:{{.src_port}} hacia la IP {{.flow_dest_ip}}:{{.dest_port}}\""
    }
   ]
  },
  {
   "title": "Recuento detecciones en el tiempo por firma",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (signature_id) (count_over_time({job=\"suricata\", signature_id=~\".*\"} [$__auto]))",
     "legendFormat": "firma: {{signature_id}}"
    }
   ]
  },
  {
   "title": "Porcentaje detecciones por firma",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (signature_id) (count_over_time({event_type=\"alert\"}[1h])) ",
     "legendFormat": "{{signature_id}}"
    }
   ]
  },
  {
   "title": "Top Attackers",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum (count_over_time({job=\"suricata\", event_type=\"alert\"} [$__auto])) by (src_ip, signature_id)",
     "legendFormat": "{{signature_id}} desde {{src_ip}}"
    }
   ]
  },
  {
   "title": "Top Victims",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum (count_over_time({job=\"suricata\", event_type=\"alert\"} [$__auto])) by (dest_ip, signature_id)",
     "legendFormat": "{{dest_ip}} atacado por {{signature_id}}"
    }
   ]
  },
  { "title": "Antrea Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Antrea Network Policy Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"networkpolicy\"} \n|  json \n|  line_format \"🛡️ {{.action}} {{.protocol}} packet from Source:{{.sourceip}}:{{.sourceport}} to Destination:{{.destinationip}}:{{.destinationport}} hitting rule {{.rulename}} with reference {{.antreaNativePolicyReference}}\""
    }
   ]
  },
  {
   "title": "Loglabels a lo largo del tiempo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"networkpolicy\", loglabel!~\"1.*]\"}[$__interval])) by (loglabel, action)",
     "legendFormat": "{{action}} / {{loglabel}}"
    }
   ]
  },
  {
   "title": "Network Policy Hits by Action",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum (count_over_time({job=\"networkpolicy\", action=~\"$action_filter\", pod=\"$namespace_filter/$pod_filter\"} [$__range])) by (action)\n",
     "legendFormat": "{{action}}"
    },
    {
     "direction": "backward",
     "expr": "sum (count_over_time({job=\"networkpolicy\"} [$__range])) by (action)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  { "title": "Kubernetes Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Tráfico entrada/salida",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{}[$__rate_interval]) ) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{}[$__rate_interval]) ) by (pod) * -1",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}