apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: siem
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:4.0.3
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/
        - name: host-var-log-suricata
          mountPath: /var/log/suricata
        - name: host-var-log-antrea
          mountPath: /var/log/antrea
      volumes:
      - name: config
        configMap:
          name: fluent-bit-config
      - name: host-var-log-suricata
        hostPath:
          path: /var/log/suricata
          type: DirectoryOrCreate
      - name: host-var-log-antrea
        hostPath:
          path: /var/log/antrea
          type: DirectoryOrCreate


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: siem
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    debug
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    [INPUT]
        Name         tail
        Path         /var/log/suricata/*.json
        Parser       suricata_json
        Tag          suricata

    [INPUT]
        Name         tail
        Path         /var/log/antrea/networkpolicy/np*.log
        Parser       antrea_np
        Tag          antreanetworkpolicy

    [FILTER]
        Name        nest
        Match       suricata
        Operation   lift
        Nested_under alert

    [FILTER]
        Name   modify
        Match  suricata
        Rename signature signature_text


    [OUTPUT]
        Name              loki
        Match             suricata
        Host              loki.siem.svc
        Port              3100
        Labels            job=suricata,src_ip=$src_ip,dest_ip=$dest_ip,proto=$proto,event_type=$event_type,signature_id=$signature_id,action=$action
        #Label_keys       src_ip,dest_ip,proto,event_type,signature_id,action
        Auto_kubernetes_labels on


    [OUTPUT]
        Name              loki
        Match             antreanetworkpolicy
        Host              loki.siem.svc
        Port              3100
        Labels            job=networkpolicy
        Label_keys        $nodename,$action,$pod,$namespace,$sourceip,$sourceport,$destinationip,$destinationport,$loglabel 
        Auto_kubernetes_labels on

    [OUTPUT]
        Name              http
        Match             suricata
        Host              alert-listener.ids.svc 
        Port              80
        URI               /alert
        Format            json_lines
        Header            Content-Type application/json

  
  parsers.conf: |

  custom_parsers.conf: |
      [PARSER]    
        Name        suricata_json
        Format      json 
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

      [PARSER]    
        Name antrea_np
        Format regex
        # https://rubular.com/r/4SHDYertUohjvP
        Regex ^(?<date>[^ ]+) (?<time>[^ ]+) (?<ovsTableName>[^ ]+) (?<antreaNativePolicyReference>[^ ]+) (?<rulename>[^ ]+) (?<direction>[^( ]+) (?<action>[^ ]+) (?<openflowpriority>[^ ]+) (?<pod>[^ ]+) (?<sourceip>[^ ]+) (?<sourceport>[^ ]+) (?<destinationip>[^ ]+) (?<destinationport>[^ ]+) (?<protocol>[^ ]+) (?<packetLength>.*) (?<loglabel>.*)$