apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: siem
data:
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      instance_addr: 127.0.0.1
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    querier:
      max_concurrent: 4096

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 500

    chunk_store_config:
      max_look_back_period: 0s
      chunk_cache_config:
        embedded_cache:
          enabled: true
          max_size_mb: 500
          ttl: 24h

    schema_config:
      configs:
        - from: 2025-06-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    limits_config:
      split_queries_by_interval: 0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: siem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: loki
          image: grafana/loki:2.9.14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3100
          args:
            - -config.file=/etc/loki/config/config.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/loki/config
            - name: loki-data-pvc
              mountPath: /loki
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: loki-data-pvc
          persistentVolumeClaim:
            claimName: loki-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: siem
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
