apiVersion: v1
kind: Pod
metadata:
  name: recovery-prometheus
  namespace: siem
spec:
  containers:
    - name: shell
      image: ubuntu
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: datos
          mountPath: /mnt/data
  volumes:
    - name: datos
      persistentVolumeClaim:
        claimName: prometheus-server
