apiVersion: v1
kind: Service
metadata:
  name: apache
  annotations:
    service.antrea.io/external-ip-pool: "service-external-ip-pool"
spec:
  selector:
    app: apache
  loadBalancerIP: "192.168.1.220"  # Primera IP del pool 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
