apiVersion: v1
kind: Service
metadata:
  name: alert-listener
  namespace: ids
  annotations:
      service.antrea.io/external-ip-pool: "service-external-ip-pool"
spec:
  selector:
    app: alert-listener
  loadBalancerIP: "192.168.1.224"
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-listener
  namespace: ids
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-listener
  template:
    metadata:
      labels:
        app: alert-listener
    spec:
      containers:
      - name: webhook
        image: lujaestfg/alert-listener:latest
        ports:
        - containerPort: 5000
        env:
        - name: PREVENTION_IDS
          value: "[100001, 100002]"  # Replace with Suricata signature IDs you want to block
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
      serviceAccountName: alert-listener-sa

---
# rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alert-listener-sa
  namespace: ids
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alert-listener-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alert-listener-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alert-listener-role
subjects:
  - kind: ServiceAccount
    name: alert-listener-sa
    namespace: ids
