apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-victim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-victim
  template:
    metadata:
      labels:
        app: apache-victim
    spec:
      containers:
      - name: apache
        image: httpd
        env:
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: apache-victim
spec:
  selector:
    app: apache-victim
  ports:
  - port: 8080
    targetPort: 8080