apiVersion: v1
kind: Pod
metadata:
  name: web-dvwa
  labels:
    app: web-dvwa
spec:
  containers:
    - name: database
      image: vulnerables/web-dvwa
      ports:
        - containerPort: 80
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: web-dvwa
  annotations:
    service.antrea.io/external-ip-pool: "service-external-ip-pool"
spec:
  selector:
    app: web-dvwa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: "192.168.1.225" 